### ISSUE TITLE
How much memory for GPU to train?

### ISSUE THREAD

**Issue by duynn912** [jshtok/RepMet#11]
Dear authors, 
Thank you for your open-source code, I am very interested in your work. However, can you please share how much memory you need to train your model to get results in your CVPR and how many GPUs you take to train, especially for COCO training? I have problems to train models following your instructions, btw my GPU has 12G.

**Comment by jshtok** [comment]
Hi,
We have also used GPUs with 12G, specifically, Tesla K40 and K80. If you set to have one image per batch, there should be no problem.
