### ISSUE TITLE
from FSD_serv import FSD_serv,get_FSD_serv_args from FSD_common_lib import gen_train_zip, assert_folder, export_dets_CSV_from_multi

### ISSUE THREAD

**Issue by shenglih** [jshtok/RepMet#15]
Hi Dr Shtok, would you mind giving some pointer what these packages are? Much appreciated.

**Comment by jshtok** [comment]
Hi @shenglih ,
There is a bigger issue here. The usecase notebooks are placed in the repository for visualization, but unfortunately they are supported by a newer version of the code that I can not yet publish.

My apologies,
Joseph
