### ISSUE TITLE
Detection results?

### ISSUE THREAD

**Issue by duynn912** [jshtok/RepMet#17]
Dear @jshtok ,

It seems your code only print out the accuracy on the command screen. Would you mind support us to save detection results such as pickle files or something like Detectron or SNIPER which is also mxnet. 

And How I can get mAP on Pascal VOC and COCO?

Thank you so much!

**Comment by jshtok** [comment]
hi,
The detection results are printed out by the print_perf() function of the PerfStats class. You can redirect its output in any way you like.
