### ISSUE TITLE
RPN classification Loss

### ISSUE THREAD

**Issue by yang-yk** [jshtok/RepMet#18]
https://github.com/jshtok/RepMet/blob/22aec096cd89a06d008fdd5b335a816545bdf073/fpn/symbols/resnet_v1_101_fpn_dcn_rcnn_oneshot_v3.py#L953

Sorry to bother you. I wonder why there is no make_loss for RPN classification loss?
@jshtok  @duynn912

**Comment by jshtok** [comment]
Hi @yang-yk,
In MXNet the SoftmaxOutput is already a loss, so there is no need for MakeLoss.

**Comment by yang-yk** [comment]
Thanks!
