### ISSUE TITLE
pretrained model not available

### ISSUE THREAD

**Issue by GallonDeng** [jshtok/RepMet#2]
not available  from https://ibm.box.com/s/g7xcm0hkyec2rd4hixfbthke8lunsyrv?

**Comment by jshtok** [comment]
Hi, indeed the link has gone bad. Please try this one:
https://ibm.box.com/s/jbpddqmlmcjq4hnaw6rr10dn60wm4vl9

**Comment by GallonDeng** [comment]
Thanks very much. very interesting work, highly expected your code release

**Comment by jshtok** [comment]
Thank you Allen,

Hope you will find this useful.

Regards,
Joseph

**Comment by shenglih** [comment]
Hi may I access the pretrained network fpn_dcn_coco as well? The updated link is outdated as well... Much appreciated!

**Comment by jshtok** [comment]
Hi,

The model is available at the shared Google Drive folder
https://drive.google.com/drive/folders/1MZ6HWQpR_Oseo5_v5gmrlAyubrPL-ciO?usp=sharing
,
as stated in the Readme.md

Regards,
Joseph
