### ISSUE TITLE
How ROI proposal works when shift to new class in few shot learning?

### ISSUE THREAD

**Issue by HochCC** [jshtok/RepMet#20]
Hi@jshtok, thanks for sharing your work!
But one question is really confusing for me,
**How can ROI proposal still work well when shift to object from new categories in few shot learning phase?**
In the normal Faster R-CNN, the ROI proposal layer generate proposals by classifying fore-/background, when a new category comes (with high visual difference), I think it may classified as background. And in your code, it seems your ROI proposal layer is pretty the same as normal Faster R-CNN. (maybe you can tell me where is the difference)

In the paper, you start from pooled feature vector directly as in below picture.
![Screenshot from 2019-12-28 19-24-40](https://user-images.githubusercontent.com/20421610/71547997-dea73a00-29a7-11ea-9296-29f681cfb2b2.png)

So how can the network generate good proposals for new categories in few shot learning with out fine-turning?

thanks!

**Comment by jshtok** [comment]
Hi,

The assumption is that new categories come from the same visual domain as
the training categories. Also, the set of training categories should be
rich to contain many objects. Then the RPN works well

Your remark is justified. When we tried to use new categories radically
different from training data, RPN was not generating good proposals.

Regards,
Joseph

**Comment by HochCC** [comment]
Hi Joseph,
thanks for your very clear reply! 

Best,
Xinjie
