### ISSUE TITLE
application - logo dataset and result?

### ISSUE THREAD

**Issue by shenglih** [jshtok/RepMet#21]
Hi @jshtok, thanks for sharing the project! A quick question about other applications - about the logo detection use case, do you mind sharing the specs of your dataset (how many annotated images of 206 classes?) and the corresponding results? Do you know what kind of applications/datasets are best suited for RepMet and what not? Thanks so much!

**Comment by jshtok** [comment]
Hi @shenglih , sorry for late response.

The logo dataset is a proprietary data, collected by IBM, so unfortunately we can't share it. However, I can say we used about 100 samples per class, ranging over most popular western logos, achieving about 90% precision at 90% recall.
RepMet has proven itself well when the few-shot categories come from the same domain as the base categories, as opposed to an abrupt change in the domain. 
Regards,
Joseph
