### ISSUE TITLE
Is there a mistake in "fpn/core/tester.py"?

### ISSUE THREAD

**Issue by marvelyou** [jshtok/RepMet#27]
Hi jshtok,

In line 272: `info_str = imdb.evaluate_detections(detections=all_boxes,logger=logger)`,  and line 345: `info_str = imdb.evaluate_detections(all_boxes,logger)`, where function `evaluate_detections` (in imagenet.py or pascal_voc.py) only has one parameter (**detections**), but two parameters are given.

This seem to trigger some errors when running "fpn/test.py"!

**Comment by jshtok** [comment]
hi @marvelyou ,
We did not use the evaluation code of the imagenet/Pascal, so it's quite possible the functions there are not addressed properly in the current code.
