### ISSUE TITLE
finetune with few shot classes

### ISSUE THREAD

**Issue by liyangliu** [jshtok/RepMet#7]
![image](https://user-images.githubusercontent.com/5159489/66287628-16eb2f00-e909-11e9-951c-14d414e73707.png)
The right part of Tab. 3 shows the results of episode fine tuning, and the paper said,
![image](https://user-images.githubusercontent.com/5159489/66287715-5a459d80-e909-11e9-8d4e-ef42e925ac63.png)

Can you explain how you actually fine tune with the episodic data, I am not so sure what is **the last layer of the network**? Thanks.

**Comment by jshtok** [comment]
Dear Liyang,

There is a 'freeze' parameter in the code, which admits values 0 (all layers are training), 1 and 2 (most layers are frozen. freeze=2 leaves the last two fully connected layers and the bounding box prediction layer unfrozen, and freeze=1  leaves only the representatives unfrozen.
We did the finetuning with the freeze=1 option.
