### ISSUE TITLE
Downloading Imagenet-LOC dataset download URL is invalid

### ISSUE THREAD

**Issue by qa8306202** [jshtok/RepMet#8]

**Comment by qa8306202** [comment]
BTW, this dataset is too big to me to test, do you have other datasets test code,such as Oxford Flowers/Pets?

**Comment by jshtok** [comment]
@qa8306202,
Unfortunately, I cannot provide you with ILSVRC data link. Please address their site , e.g. http://image-net.org/

Also, we did not test on other datasets. However, you can adjust the code to work with any dataset by controlling the 'dataset' section of the configuration yaml (and having the corresponding dataset class and data)
